# -*- coding: utf-8 -*-
"""Test_Chicuadrado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAaFb0DSGnskXD4raG-hhII7cVRCD60g
"""

import numpy as np
import scipy.stats as stats

# Datos observados en la tabla de doble entrada
observed = np.array([[9, 37], [7, 28]])

# Aplicar la prueba de Chi-Cuadrado
chi2, p_value, dof, expected = stats.chi2_contingency(observed)

# Mostrar los resultados
print(f"Estadístico Chi-Cuadrado: {chi2:.4f}")
print(f"P-valor: {p_value:.4f}")
print(f"Grados de libertad: {dof}")
print("\nTabla Esperada:")
print(expected)